---
stages:
  - lint
  - build
  - publish
  - release

include:
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.3.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-lint
    ref: 2.1.1
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-build
    ref: 4.3.3
    file: gitlab-ci-build.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 3.6.0
    file: gitlab-ci.yml

variables:
  APP_NAME: git-tools
  DOCKER_DISABLE_ALL_JOBS: 'true'
  DOCKER_PUBLIC_REPO: vptech
  PUBLIC: 'true'
  SEMANTIC_CONFIG_FILE: changelog

public:1.1.0:
  extends: .publish-public:docker
  variables:
    DOCKER_BUILD_ARGS: --build-arg GLAB_VERSION=1.11.1 --build-arg HUB_VERSION=2.14.2 --build-arg LAB_VERSION=0.17.2
    TAG: 1.1.0
...
